mutation uploadParticipants (
    $email: String
    $name: String
    $title: String
) {
    uploadParticipants ( data: {
        email: $email,
        name: $name,
        title: $title
    }) 
    {   participant {
           id 
           name 
        }
    } 
}